## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(tz2NM4GcmnE7sNJTYL8ZSg==)
      client-secret: ENC(tz2NM4GcmnE7sNJTYL8ZSg==)
      scope: server

## 定时任务
spring:
  # 保存定时任务的数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:  root
    url: jdbc:mysql://laonog-mysql:3306/laonog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: laonog-zookeeper:2181
      namespace: laonog-daemon
    # 普通任务
    simples:
      spring-simple-job:
        job-class: com.laonog.daemon.job.LaonogSimpleJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.laonog.daemon.listener.LaonogElasticJobListener
      spring-simple-job2:
        job-class: com.laonog.daemon.job.LaonogSimpleJob2
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.laonog.daemon.listener.LaonogElasticJobListener
    # 简单任务
    dataflows:
      spring-dataflow-job:
        job-class: com.laonog.daemon.job.LaonogDataflowJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        streaming-process: true
        eventTraceRdbDataSource: 'dataSource'
        listener:
          distributed-listener-class: com.laonog.daemon.listener.LaonogDistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000
