# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:  root
    url: jdbc:mysql://laonog-mysql:3306/laonog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
