server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 6788
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.95.70:3306/canbu?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: beyondsoft
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

# Mybatis

mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.laonog.generator.entity

